services:
  db:
    image: postgres:17.0
    container_name: go_postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-123456}
      POSTGRES_DB: ${DB_NAME:-postgres}
    ports:
      - "${DB_PORT:-5431}:5431"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - zizone-net
    command: ["postgres", "-p", "5431"]

  redis:
    image: redis:8.0
    container_name: go_redis
    restart: always
    ports:
      - "${REDIS_PORT:-6378}:6378"
    volumes:
      - redis_data:/data
    networks:
      - zizone-net
    command: ["redis-server", "--port", "6378"]

  app:
    build: .
    container_name: go_app
    restart: always
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=${DB_HOST:-localhost}
      - DB_PORT=${DB_PORT:-5432}
      - DB_USER=${DB_USER:-postgres}
      - DB_PASSWORD=${DB_PASSWORD:-123456}
      - DB_NAME=${DB_NAME:-postgres}
      - REDIS_HOST=${REDIS_HOST:-redis}
      - REDIS_PORT=${REDIS_PORT:-6379}
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS:-http://localhost:3000,http://localhost:5173}
      - ACCESS_JWT_SECRET=${ACCESS_JWT_SECRET:-website_zizone}
      - MAIL_USER=${MAIL_USER:-talonlongkiem22@gmail.com}
      - MAIL_PASS=${MAIL_PASS:-gjae ovdd icbk gxfx}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID:-825850566727-2u0jtncv8v5p8koo04cbafh0ak8f4r18.apps.googleusercontent.com}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET:-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}
      - GOOGLE_REDIRECT_URI=${GOOGLE_REDIRECT_URI:-http://localhost:3000/sign-in}
    depends_on:
      - db
      - redis
    networks:
      - zizone-net

networks:
  zizone-net:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
